### ISSUE TITLE
两个问题

### ISSUE THREAD

**Issue by Json-Luo** [apanly/mooc#1]
1.阿里云的源怎么没有1.8的 nginx   这些软件的版本太低了  哪个源有高一点的版本  我用默认的源也找不到 nginx1.8的   还是说受限于 ubuntu1404 这个系统 ?
2. 冒昧的问一下有 ubuntu16 LTS 的 box 么?? thanks

**Comment by apanly** [comment]
关于第一个问题，的确每一个ubuntu版本都有对应的官方指定的软件版本
关于第二个问题，我这边有,16.04的nginx 版本是1.10 ，下载地址 https://pan.baidu.com/s/1mhXg6Vm

**Comment by Json-Luo** [comment]
首先感谢大神给小白指点疑惑
现在我已经解决了 ubuntu1604的环境了  所有软件都安装成功并且运行了  但是我的私有网络配置不正确 ( 只能显示 nginx 的首页  我装的是 nginx 1.10的  php7.0的 扩展都装了  mysql 5.7的)  文件共享是 OK 的   但是配置不了 laravel 的环境   页面也不报错  就是不能访问 chrome 会提示一个错误"Failed to load resource: net::ERR_NAME_NOT_RESOLVED"  如何解决   其他功能都能实现    就是不能根据文件共享来配置框架环境

我的配置
server {
    listen 80;
    server_name dev.linger.com; ( 这边在 hosts 文件也配置过了 )
    charset utf-8;

    root /home/www/linger/public;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9000; ( 这边配置过了 也重启服务了 )
        try_files $uri = 404;
    }
}

**Comment by Json-Luo** [comment]
老师辛苦了, 这个问题我已经解决了   是因为我没在主机中配置 域名解析到静态 ip 上面    我以为是在虚拟机里面配置 hosts 文件   导致本机中输入域名无法解析到虚拟机中    在此非常感谢老师给我一把神器   希望老师能出一期 docker 的教学
